[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Dependencies for the ToF sensor and micro-ROS
lib_deps =
    pololu/VL53L1X @ ^1.3.1
    https://github.com/micro-ROS/micro_ros_platformio

board_microros_distro = jazzy
board_microros_transport = serial




;Guide of Setup for micro-ROS on ESP32 using PlatformIO
;
;project file
;1) create project directory then cd
;2) pio project init
;3) add main.cpp in src
;4) modify platformio.ini
;5) pio run
;6) pio run -t upload
;
;microros agent
;1) download microros
;2) skip creating new firmware as we create our custom one by pio alr
;3) download microros agent package -
;	ros2 run micro_ros_setup create_agent_ws.sh
;4) build and source -
;	ros2 run micro_ros_setup build_agent.sh
;	source install/local_setup.bash
;5) run the microros agent -
;	ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyUSB1
;	can use ls /dev/tty* to find device
